[build-system]
# here we specify the build-backend. For context:
# - tools like pip and uv are example of build-frontends. Users directly
#   interact with the frontend
# - tools like setuptools, flit, scikit-build-core, meson-python are all
#   examples of build backends
requires = [
  # the version bound follows modern conventions for license & license-files
  "hatchling>=1.26",
  # a plugin that infers the version number from git tags
  "hatch-vcs",
]
build-backend = "hatchling.build"

[project]
name = "pah_spec"
license = "MIT"
license-files = ["LICENSE"]
# detect the version number from the __version__ variable in _version.py
dynamic = ["version"]
# we may need to adjust the version bounds
requires-python = ">=3.9"
description = "tool for generating PAH spectra with the single photon approximation"
readme = "README.md"
authors = [{name = "Helena Richie", email = "helenarichie@gmail.com"}]
classifiers = [
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Unix",
  "Natural Language :: English",
  "Programming Language :: C++",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
]
# we should probably add version bounds
dependencies = [
  'astropy',
  'numpy',
  'pandas',
  'scipy >= 1.6.0',
  'h5py',
  # we may need to bumpy the lower limit
  'pooch >= 1.1, <2'
]

[project.urls]
Homepage = 'https://github.com/helenarichie/pah_spec'
Documentation = 'https://pah-spec.readthedocs.io/'
Source = 'https://github.com/helenarichie/pah_spec'
Tracker = 'https://github.com/helenarichie/pah_spec/issues'

[dependency-groups]
# these are development dependencies. They can be installed with pip (v25.1+)
# by invoking `pip install --user --group dev` from the directory holding this
# configuration file
docs = [
    'myst_parser',
    'sphinx',
    'sphinx_inline_tabs',
    'sphinx_rtd_theme'
]
test = ["pytest"]
dev = [{include-group = "docs"}, {include-group = "test"}]

# hatch-specific instructions
[tool.hatch]
version.source = "vcs"
# the build-system automatically generates a file with the following name
# that includes the version
build.hooks.vcs.version-file = "src/pah_spec/_version.py"

[tool.hatch.build.targets.sdist]
# explicitly include the _version.py file in a sdist. It is dynamically created
# by hooks during the build-process. (We need to explicitly include it since its
# in our .gitignore file, which hatch uses for determining sdist contents)
artifacts = ["src/pah_spec/_version.py"]
# the following files/directories really aren't needed in a sdist
exclude = [
  "data/**",
  "examples/**",
  # if we are excluding data, then there's no reason to include tests
  # (unless we rewrite the tests to actually download the data that they need)
  "tests/**",
  ".github/**",
  ".pre-commit-config.yaml"
]

[tool.hatch.build.targets.wheel]
# explicitly include the _version.py file in a wheel. It is dynamically created
# by hooks during the build-process. (We need to explicitly include it since its
# in our .gitignore file, which hatch uses for determining wheel contents)
artifacts = ["src/pah_spec/_version.py"]
# the following files/directories really aren't needed in a wheel
exclude = [
  # unneeded directories:
  "data/**",
  "docs/**",
  "examples/**",
  "tests/**",
  ".git/**",
  ".github/**",
  # unneeded files:
  ".git_archival.txt",
  ".gitattributes",
  ".pre-commit-config.yaml"
]

# configure pytest
[tool.pytest.ini_options]
# settings inspired by: learn.scientific-python.org/development/guides/pytest/
#  -ra: The -r tells pytest to report extra test summary info on the events
#       corresponding to all characters following the r. Here, the "a"
#       corresponds to "all" events (other than passing tests)
#  --showlocals: directs pytest to show local variables in tracebacks
#  --strict-markers: ensures we don't try to use an unspecified fixture
#  --string-config: all configuration mistakes are reported as errors
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
# by default, we treat any test marked xfail that doesn't fail as an error
# (we can override this locally, if necessary)
xfail_strict = true
# limit the directories searched by pytests for the test files
testpaths = [
  "tests",
]
